robot:
  model:          ur5
  planning_group: ur_manipulator
  ee_link:        tool0
  base_link:      base_link
  velocity_scaling:      0.3
  acceleration_scaling:  0.3
  joint_names:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  home_position:
    shoulder_pan_joint:   0.0
    shoulder_lift_joint:  -1.57
    elbow_joint:          1.57
    wrist_1_joint:        -1.57
    wrist_2_joint:        -1.57
    wrist_3_joint:         0.0
